### ISSUE TITLE
Hope to integrate nodejs api

### ISSUE THREAD

**Issue by yizhiyan** [neutralinojs/roadmap#4]
Hope to be able to integrate nodejs api, if this is an optional configuration, it would be great. Although this is a little conflict with your design, if I can introduce it, I will use various npm modules easily, thank you.

**Comment by shalithasuranga** [comment]
Hello.. Thanks for the suggestion. This is possible with the current implementation of Neutralinojs via API extensions feature. There are two ways to build Neutralinojs with Node.
- Calling Neutralino via Node child process and communicate via child process IPC.
- Using a node script as an API extension. (See: sample: https://github.com/neutralinojs/neutralinojs/blob/main/bin/extensions/sampleextension/main.js)

I am closing this because we will release extensions API with the next release.
